#!/bin/bash
# TÜM KOD DENETİMLERİ — her paket öncesi çalıştırılır.
# Hiçbiri veriye dokunmaz; sadece kaynak dosyaları okur.
cd "$(dirname "$0")/.."
echo "── KOD DENETİMLERİ ──"
python3 testler/jsxdenetle.py  src/*.jsx src/*.js api/*.js lib/*.js > /dev/null && echo "✓ 1 sözdizimi"
# 1b: GERÇEK ayrıştırma. Yukarıdaki sezgisel denetim bir import satırındaki çift virgülü
#     kaçırdı ve "✓" dedi; derleme ise patladı. Derleyicinin kendisi son sözü söylesin.
node testler/gercekSozdizimi.mjs > /dev/null && echo "✓ 1b gerçek ayrıştırma (esbuild)"
python3 testler/bozulma.py     src/*.jsx                            > /dev/null && echo "✓ 2 şablon bozulması"
python3 testler/ciftdenetle.py src/*.jsx api/*.js lib/*.js          > /dev/null && echo "✓ 3 çift tanım"
python3 testler/jsxyapi.py     src/*.jsx                            > /dev/null && echo "✓ 4 JSX yapısı"
python3 testler/ikondenetle.py src/*.jsx                            > /dev/null && echo "✓ 5 eksik bileşen/ikon"
python3 testler/hookdenetle.py src/*.jsx src/*.js                   > /dev/null && echo "✓ 6 React hook'ları"
python3 testler/cagridenetle.py src/*.jsx src/*.js api/*.js lib/*.js | grep "^✗" | grep -v "Ciro\|Tamamlananlar" || echo "✓ 7 tanımsız çağrı yok"
python3 testler/butondenetle.py src/*.jsx                           > /dev/null && echo "✓ 8 buton bağlantıları"
python3 testler/exportdenetle.py src/*.jsx src/*.js api/*.js lib/*.js > /dev/null && echo "✓ 9 eksik export yok"
python3 testler/degiskendenetle.py src/*.jsx                        > /dev/null && echo "✓ 10 JSX'te tanımsız değişken yok"
python3 testler/musteriAlanDenetle.py                               > /dev/null && echo "✓ 11 müşteri paneli alanları düşmüyor"
python3 testler/kapsamdenetle.py src/*.jsx                          > /dev/null && echo "✓ 12 kapsam dışı kullanım yok"
python3 testler/olusetter.py src/*.jsx                              > /dev/null && echo "✓ 13 değiştirilemeyen durum yok"
python3 testler/kullanimdenetle.py src/*.jsx api/*.js lib/*.js       > /dev/null && echo "✓ 14 yayılımda gelmeyen ad yok"
python3 testler/ekrandenetle.py                                     > /dev/null && echo "✓ 15 ekran öğeleri yerinde"
python3 testler/sabitdenetle.py src/*.jsx api/*.js lib/*.js         > /dev/null && echo "✓ 16 tanımsız sabit yok"
python3 testler/erisimdenetle.py src/*.jsx                          > /dev/null && echo "✓ 17 erişilemeyen ad yok"
node testler/sistemBelgesi.mjs                                      > /dev/null && echo "✓ 18 sistem belgesi envanteri güncel"
node testler/fonksiyonSayisi.mjs                                    > /dev/null && echo "✓ 19 api fonksiyon sayısı sabiti güncel"
node testler/temaAnahtari.mjs                                       > /dev/null && echo "✓ 20 tema anahtarları gerçek"
node testler/yanitAlanlari.mjs                                      > /dev/null && echo "✓ 21 yanıt alanı belgeye sızmıyor"
echo ""
echo "── SUNUCU DENETİMLERİ ──"
echo "(testler/ klasöründe: node t5.mjs … t11.mjs — sahte veritabanı kullanır, gerçek veriye dokunmaz)"
