export const DEFAULT_DATA = {
  firmaAdi: "Marcus Medya",
  markaKimligiGorseli: null,
  teklifler: [],
  teklifSablonlari: [],
  sozlesmeSablonlari: [],
  reklamlar: [],
  stoklar: {},
  paylasimGecmisi: [],
  cekimIsleri: [],
  gunlukKontrol: null,
  haftalikPaylasimlar: [],
  hesaplar: [{ id: "ana", ad: "Marcus Medya", anaHesap: true }],
  hesapTransferleri: [],
  staffPermissions: {
    dashboard: false, musteriler: false, finans: false, takvim: false, odemeTakvimi: false,
    teklif: false, reklamlar: true, paylasimlar: true, cekimEdit: true, personel: false, birikim: false,
  },
  monthly: [
    { id: 1, ay: "Şub", yil: 2026, ciro: 168000, gider: 98000, net: 70000 },
    { id: 2, ay: "Mar", yil: 2026, ciro: 182000, gider: 101000, net: 81000 },
    { id: 3, ay: "Nis", yil: 2026, ciro: 176000, gider: 104000, net: 72000 },
    { id: 4, ay: "May", yil: 2026, ciro: 195000, gider: 108000, net: 87000 },
    { id: 5, ay: "Haz", yil: 2026, ciro: 210000, gider: 112000, net: 98000 },
    { id: 6, ay: "Tem", yil: 2026, ciro: 231000, gider: 119000, net: 112000 },
  ],
  clients: [
    { id: 1, ad: "Nova Teknoloji", kategori: "Yazılım", durum: "aktif", aylikUcret: 58000, karMarji: 71, baslangic: "2024-11", not: "En kârlı müşteri", maliyetler: [], odemeGunu: 5, odemeler: [], odemeKayitlari: [], faturaliTutar: 58000 },
    { id: 2, ad: "Lezzet Sofrası", kategori: "Restoran Zinciri", durum: "aktif", aylikUcret: 45000, karMarji: 62, baslangic: "2024-06", not: "", maliyetler: [], odemeGunu: 10, odemeler: [], odemeKayitlari: [], faturaliTutar: 45000 },
    { id: 3, ad: "UrbanFit Spor Kulübü", kategori: "Spor & Wellness", durum: "aktif", aylikUcret: 32000, karMarji: 55, baslangic: "2025-01", not: "", maliyetler: [], odemeGunu: null, odemeler: [], odemeKayitlari: [], faturaliTutar: 32000 },
    { id: 4, ad: "Mavi Deniz Otelcilik", kategori: "Turizm", durum: "yeni", aylikUcret: 40000, karMarji: 48, baslangic: "2026-06", not: "Ödemenin yarısı nakit, yarısı faturalı", maliyetler: [], odemeGunu: null, odemeler: [], odemeKayitlari: [], faturaliTutar: 20000 },
    { id: 5, ad: "Yeşil Bahçe Peyzaj", kategori: "Peyzaj & Bahçe", durum: "aktif", aylikUcret: 18000, karMarji: 28, baslangic: "2025-03", not: "En düşük kârlı müşteri", maliyetler: [], odemeGunu: null, odemeler: [], odemeKayitlari: [], faturaliTutar: 0 },
    { id: 6, ad: "Altın Kuyumcu", kategori: "Perakende", durum: "ayrildi", aylikUcret: 0, karMarji: 0, baslangic: "2024-02", not: "", maliyetler: [], odemeGunu: null, odemeler: [], odemeKayitlari: [], faturaliTutar: 0 },
  ],
  gelirKalemleri: [
    { id: 1, kalem: "Aylık Yönetim Bedelleri", tutar: 193000, tekrar: "sabit", faturali: "evet" },
    { id: 2, kalem: "Proje Bazlı Çekimler", tutar: 28000, tekrar: "tek seferlik", faturali: "evet" },
    { id: 3, kalem: "Reklam Yönetim Komisyonu", tutar: 10000, tekrar: "sabit", faturali: "evet" },
  ],
  giderKalemleri: [
    { id: 2, kalem: "Ekipman & Kiralama", tutar: 14000, tekrar: "tek seferlik" },
    { id: 3, kalem: "Reklam Harcaması (Müşteri Adına)", tutar: 22000, tekrar: "tek seferlik" },
    { id: 5, kalem: "Yazılım & Araçlar", tutar: 6000, tekrar: "sabit" },
  ],
  ofisGiderleri: [
    { id: 1, kalem: "Kira", tutar: 15000, tekrar: "sabit" },
    { id: 2, kalem: "Elektrik", tutar: 1200, tekrar: "sabit" },
    { id: 3, kalem: "Su", tutar: 300, tekrar: "sabit" },
    { id: 4, kalem: "İnternet", tutar: 800, tekrar: "sabit" },
    { id: 5, kalem: "Aidat", tutar: 700, tekrar: "sabit" },
  ],
  bekleyenTahsilatlar: [
    { id: 1, musteri: "Mavi Deniz Otelcilik", tutar: 40000, vade: "3 gün gecikti" },
    { id: 2, musteri: "Yeşil Bahçe Peyzaj", tutar: 18000, vade: "bugün" },
  ],
  personel: [
    { id: 1, ad: "Ege Aydın", pozisyon: "Video Editörü", maas: 32000, sigorta: 9500, yemek: 3500, tazminatBirikimi: 1500, baslangic: "2024-09" },
    { id: 2, ad: "Deniz Kara", pozisyon: "Sosyal Medya Uzmanı", maas: 26000, sigorta: 8000, yemek: 3500, tazminatBirikimi: 1200, baslangic: "2025-02" },
  ],
  birikimler: [
    { id: 1, ad: "Kıdem Tazminatı Fonu", hedefTutar: 60000, not: "Ege ve Deniz için aylık birikim", bakiye: 8100, hareketler: [
      { id: 1, tip: "ekleme", tutar: 2700, tarih: "05.07.2026", not: "Haziran payı" },
      { id: 2, tip: "ekleme", tutar: 2700, tarih: "05.06.2026", not: "Mayıs payı" },
      { id: 3, tip: "ekleme", tutar: 2700, tarih: "05.05.2026", not: "Nisan payı" },
    ] },
    { id: 2, ad: "Acil Müdahale Fonu", hedefTutar: 100000, not: "Beklenmedik giderler için", bakiye: 35000, hareketler: [
      { id: 1, tip: "ekleme", tutar: 35000, tarih: "01.06.2026", not: "" },
    ] },
  ],
  vergiTakvimi: [
    { id: 1, kalem: "KDV Beyannamesi", tarih: "26 Ağu", durum: "yaklaşıyor" },
    { id: 2, kalem: "Muhtasar Beyanname", tarih: "26 Ağu", durum: "yaklaşıyor" },
    { id: 3, kalem: "Geçici Vergi (3. Dönem)", tarih: "17 Kas", durum: "planlandı" },
  ],
};
